spring.application.name=loginAuth

server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=""
spring.datasource.username=""
spring.datasource.password=""
spring.datasource.driver-class-name=""

spring.jpa.properties.hibernate.format_sql=true
jwt.auth.app=DEMO
jwt.auth.secret_key=""
jwt.auth.expires_in=36000000


